# Wikipedia (ja)
wp:
  url: 'http://ja.wikipedia.org/wiki/%s'
  enable_pc: true
  enable_mobile: false
  attributes:
    target: _blank

# OpenPNE Plugins
opplug:
  url: 'http://plugins.openpne.jp/package/%s'
  enable_pc: true
  enable_mobile: false
  attributes:
    target: _blank

# 接頭辞が省略された場合のデフォルトのリンク先
default:
  url: 'http://example.com/wiki/%s'
  enable_pc: true
  enable_mobile: false
  attributes:
    target: _blank

<?php $base = sfConfig::get('op_base_url'); ?>

# SNS内へのリンク
member: <?php echo $base.'/member/%s'."\n"; ?>
commu: <?php echo $base.'/community/%s'."\n"; ?>
community: <?php echo $base.'/community/%s'."\n"; ?>

## 以下は別途プラグインが必要
<?php $plugins = ProjectConfiguration::getActive()->getPlugins() ?>

# opDiaryPlugin
<?php if (in_array('opDiaryPlugin', $plugins)): ?>
diary: <?php echo $base.'/diary/%s'."\n"; ?>
<?php endif ?>

# opAlbumPlugin
<?php if (in_array('opAlbumPlugin', $plugins)): ?>
album: <?php echo $base.'/album/%s'."\n"; ?>
<?php endif ?>

#opCommunityTopicPlugin
<?php if (in_array('opCommunityTopicPlugin', $plugins)): ?>
topic: <?php echo $base.'/communityTopic/%s'."\n"; ?>
event: <?php echo $base.'/communityEvent/%s'."\n"; ?>
<?php endif ?>
